server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

pac4j:
  configFactory: org.pac4j.demo.dw.DemoConfigFactory

logging:
  level: INFO
  loggers:
    org.pac4j: DEBUG
    org.ldaptive: DEBUG
