server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

pac4j:
  callbackUrl: /callback
  ajaxRequestResolver:
    class: org.pac4j.core.http.ajax.DefaultAjaxRequestResolver
  clientsProperties:
    cas.loginUrl: https://casserverpac4j.herokuapp.com/login
    anonymous: fakevalue
    ldap.type: direct
    ldap.url: ldap://ldap.jumpcloud.com:389
    ldap.useStartTls: false
    ldap.useSsl: false
    ldap.dnFormat: uid=%s,ou=Users,o=58e69adc0914b437324e7632,dc=jumpcloud,dc=com
    ldap.usersDn: ou=Users,o=58e69adc0914b437324e7632,dc=jumpcloud,dc=com
    ldap.principalAttributeId: uid
    ldap.principalAttributes: mail
    ldap.enhanceWithEntryResolver: false
    formClient.loginUrl: /login.html
    formClient.authenticator: ldap
    encoder.spring.type: standard
    encoder.spring.standard.secret: salt
    db.jdbcUrl: jdbc:h2:mem:test
    # username/password to authenticate on the DB
    db.username: username
    db.password: password
    # pac4j username, password and other attributes stored in the columns
    db.usernameAttribute: username
    db.userPasswordAttribute: password
    db.userAttributes: firstname
    db.passwordEncoder: encoder.spring
    indirectBasicAuth.authenticator: db
    indirectBasicAuth.realName: DB authentication realm
    directBasicAuth.authenticator: testUsernamePassword
  authorizers:
    mustBeAuth:
      class: org.pac4j.core.authorization.authorizer.IsAuthenticatedAuthorizer
      redirectionUrl: /?mustBeAuth
    mustBeAnon:
      class: org.pac4j.core.authorization.authorizer.IsAnonymousAuthorizer
      redirectionUrl: /?mustBeAnon

logging:
  level: INFO
  loggers:
    org.pac4j: DEBUG
    org.ldaptive: DEBUG
